# Generated by Django 5.2.8 on 2025-12-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manitas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_id', models.CharField(help_text='ID del ejercicio (ej: A, NUM_3, DEPT_SAN_MIGUEL, HOLA)', max_length=100)),
                ('category', models.CharField(choices=[('alfabeto', 'Alfabeto'), ('numeros', 'Números'), ('departamentos', 'Departamentos'), ('saludos', 'Saludos Básicos')], max_length=20)),
                ('media_type', models.CharField(choices=[('image', 'Imagen'), ('video', 'Video')], max_length=10)),
                ('media_file', models.FileField(help_text='Subí una imagen para letras/números o un video para departamentos/saludos', upload_to='sign_standards/')),
                ('description', models.TextField(blank=True, help_text='Descripción opcional del estándar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si este estándar está activo')),
            ],
            options={
                'verbose_name': 'Estándar de Seña',
                'verbose_name_plural': 'Estándares de Señas',
                'ordering': ['category', 'exercise_id'],
                'unique_together': {('exercise_id', 'category', 'media_type')},
            },
        ),
    ]
