# Generated by Django 5.2.8 on 2025-12-09 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manitas', '0002_signstandard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signstandard',
            name='media_file',
            field=models.FileField(blank=True, help_text='Archivo principal (deprecated, usar media_files)', null=True, upload_to='sign_standards/'),
        ),
        migrations.CreateModel(
            name='SignStandardMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.FileField(help_text='Archivo multimedia (imagen o video)', upload_to='sign_standards/')),
                ('hand_preference', models.CharField(choices=[('ambas', 'Ambas manos'), ('izquierda', 'Mano izquierda'), ('derecha', 'Mano derecha')], default='ambas', help_text='Preferencia de mano para esta variante', max_length=10)),
                ('variant_description', models.CharField(blank=True, help_text="Descripción de la variante (ej: 'Vista frontal', 'Vista lateral')", max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='manitas.signstandard')),
            ],
            options={
                'verbose_name': 'Archivo Multimedia del Estándar',
                'verbose_name_plural': 'Archivos Multimedia de Estándares',
                'ordering': ['standard', 'order', 'id'],
            },
        ),
    ]
