# Generated by Django 5.2.8 on 2025-12-09 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manitas', '0003_alter_signstandard_media_file_signstandardmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='perfil_images/'),
        ),
    ]
